version: '3'

networks:
  service:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - service
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

 # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - service
    image: openzipkin/zipkin
    ports:
      - 9411:9411
