version: '3'

networks:
  service:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - service
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

 # This sidecar allows for the viewing of traces.
  jaeger:
    container_name: jaeger
    networks:
      - service
    image: jaegertracing/all-in-one
    ports:
      - 14268:14268
      - 16686:16686
